"""Deterministic local execution for validated candidate test suggestions.

Execution is deliberately opt-in and limited to candidates that already passed
local validation. This module never executes candidate-provided code, evaluates
expressions, runs SQL, shells out, or imports modules based on candidate input.
It only applies fixed pandas/Python logic for the supported candidate test types
and writes aggregate-only metrics for human review.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from typing import Any

import pandas as pd

from data_test_suggestion_agent.candidate_models import ValidatedCandidate

PASSED_STATUS = "passed"
FAILED_STATUS = "failed"
__test__ = False

EXECUTION_NOTES = [
    "validated_candidate_executed_locally",
    "not_an_approved_test",
]


@dataclass(frozen=True)
class TestExecutionResult:
    """Aggregate-only result for one locally executed validated candidate."""

    __test__ = False

    test_id: str
    test_type: str
    column: str | None
    severity: str
    status: str
    evaluated_row_count: int
    failure_count: int
    failure_ratio: float
    metrics: dict[str, Any] = field(default_factory=dict)
    execution_notes: list[str] = field(default_factory=lambda: list(EXECUTION_NOTES))

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable aggregate-only execution result."""
        return asdict(self)


@dataclass(frozen=True)
class TestExecutionSummary:
    """Summary counts for deterministic candidate execution."""

    __test__ = False

    validated_candidate_count: int
    executed_count: int
    passed_count: int
    failed_count: int

    def to_dict(self) -> dict[str, int]:
        """Return summary counts as a JSON-serializable dictionary."""
        return asdict(self)


def execute_validated_candidates(
    *,
    dataframe: pd.DataFrame,
    validated_candidates: list[ValidatedCandidate],
    reference_date: date | None = None,
) -> list[TestExecutionResult]:
    """Execute only validated candidates using deterministic pandas/Python logic.

    Rejected candidates are not accepted by this API. Failed check outcomes are
    represented as result status ``failed`` and are not process/CLI failures;
    they are data-quality signals for human review, not approvals or final tests.
    """
    execution_reference_date = reference_date or datetime.now(timezone.utc).date()
    return [
        _execute_candidate(
            dataframe=dataframe,
            candidate=validated_candidate,
            reference_date=execution_reference_date,
        )
        for validated_candidate in validated_candidates
    ]


def build_test_execution_results_artifact(
    *,
    validated_candidate_count: int,
    execution_results: list[TestExecutionResult],
    candidate_tests_generated_by_this_agent: bool = False,
    llm_called: bool = False,
) -> dict[str, Any]:
    """Build the aggregate-only test execution JSON artifact.

    The artifact explicitly preserves the authority boundary: candidates were
    not generated by this agent, no LLM was called, execution was local-only,
    raw rows/example values are excluded, and validated candidates are still not
    approved, official, final, or automatically correct tests.
    """
    passed_count = sum(1 for result in execution_results if result.status == PASSED_STATUS)
    failed_count = sum(1 for result in execution_results if result.status == FAILED_STATUS)
    summary = TestExecutionSummary(
        validated_candidate_count=validated_candidate_count,
        executed_count=len(execution_results),
        passed_count=passed_count,
        failed_count=failed_count,
    )
    return {
        "artifact_name": "test_execution_results",
        "execution_status": "completed",
        "candidate_tests_generated_by_this_agent": candidate_tests_generated_by_this_agent,
        "llm_called": llm_called,
        "validated_candidates_are_approved_tests": False,
        "tests_executed": True,
        "execution_is_local_only": True,
        "raw_rows_included": False,
        "example_values_included": False,
        "summary": summary.to_dict(),
        "execution_results": [result.to_dict() for result in execution_results],
    }


def _execute_candidate(
    *,
    dataframe: pd.DataFrame,
    candidate: ValidatedCandidate,
    reference_date: date,
) -> TestExecutionResult:
    """Dispatch one validated candidate to the fixed executor for its test type."""
    suggestion = candidate.candidate
    column = suggestion.column
    if column is None or column not in dataframe.columns:
        # Validation should prevent this branch. It remains aggregate-only and
        # deterministic rather than exposing rows or attempting recovery.
        return _result(
            candidate=candidate,
            evaluated_row_count=0,
            failure_count=1,
            metrics={"execution_contract_error": "validated_column_missing"},
        )

    series = dataframe[column]
    if suggestion.test_type == "not_null":
        null_count = int(series.isna().sum())
        return _result(
            candidate=candidate,
            evaluated_row_count=int(len(series)),
            failure_count=null_count,
            metrics={"null_count": null_count},
        )

    non_null = series[series.notna()]
    evaluated_row_count = int(len(non_null))

    if suggestion.test_type == "unique":
        duplicated_mask = non_null.duplicated(keep=False)
        failure_count = int(duplicated_mask.sum())
        duplicate_value_count = int(non_null[duplicated_mask].nunique(dropna=True))
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=failure_count,
            metrics={"duplicate_value_count": duplicate_value_count},
        )

    if suggestion.test_type == "accepted_values":
        allowed_values = suggestion.parameters["allowed_values"]
        failure_count = int((~non_null.isin(allowed_values)).sum())
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=failure_count,
            metrics={
                "nulls_ignored": True,
                "allowed_value_count": len(allowed_values),
            },
        )

    if suggestion.test_type == "numeric_range":
        numeric_values = pd.to_numeric(non_null, errors="coerce")
        invalid_numeric_count = int(numeric_values.isna().sum())
        failure_mask = pd.Series(False, index=non_null.index)
        if "min" in suggestion.parameters:
            failure_mask = failure_mask | (numeric_values < suggestion.parameters["min"])
        if "max" in suggestion.parameters:
            failure_mask = failure_mask | (numeric_values > suggestion.parameters["max"])
        metrics = {"nulls_ignored": True}
        if "min" in suggestion.parameters:
            metrics["min_bound"] = suggestion.parameters["min"]
        if "max" in suggestion.parameters:
            metrics["max_bound"] = suggestion.parameters["max"]
        if invalid_numeric_count:
            metrics["numeric_parse_failure_count"] = invalid_numeric_count
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=int(failure_mask.sum()) + invalid_numeric_count,
            metrics=metrics,
        )

    if suggestion.test_type == "date_parseable":
        parsed_dates = _parse_dates(non_null)
        failure_count = int(parsed_dates.isna().sum())
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=failure_count,
            metrics={"nulls_ignored": True},
        )

    if suggestion.test_type == "date_not_future":
        parsed_dates = _parse_dates(non_null)
        parse_failure_count = int(parsed_dates.isna().sum())
        reference_timestamp = pd.Timestamp(reference_date)
        future_date_count = int((parsed_dates.dropna() > reference_timestamp).sum())
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=parse_failure_count + future_date_count,
            metrics={
                "nulls_ignored": True,
                "parse_failure_count": parse_failure_count,
                "future_date_count": future_date_count,
                "reference_date": reference_date.isoformat(),
            },
        )

    if suggestion.test_type == "regex_match":
        # Patterns are compiled during validation and again here defensively.
        # The executor performs deterministic full-string matching only; it
        # never evaluates candidate text as executable code.
        compiled = re.compile(suggestion.parameters["pattern"])
        failure_count = int(
            sum(compiled.fullmatch(str(value)) is None for value in non_null)
        )
        return _result(
            candidate=candidate,
            evaluated_row_count=evaluated_row_count,
            failure_count=failure_count,
            metrics={
                "nulls_ignored": True,
                "pattern_length": len(suggestion.parameters["pattern"]),
            },
        )

    return _result(
        candidate=candidate,
        evaluated_row_count=0,
        failure_count=1,
        metrics={"execution_contract_error": "unsupported_validated_test_type"},
    )


def _result(
    *,
    candidate: ValidatedCandidate,
    evaluated_row_count: int,
    failure_count: int,
    metrics: dict[str, Any],
) -> TestExecutionResult:
    """Create a result with deterministic status and ratio fields."""
    suggestion = candidate.candidate
    return TestExecutionResult(
        test_id=suggestion.test_id,
        test_type=suggestion.test_type,
        column=suggestion.column,
        severity=suggestion.severity,
        status=PASSED_STATUS if failure_count == 0 else FAILED_STATUS,
        evaluated_row_count=evaluated_row_count,
        failure_count=failure_count,
        failure_ratio=_failure_ratio(failure_count, evaluated_row_count),
        metrics=metrics,
    )


def _failure_ratio(failure_count: int, evaluated_row_count: int) -> float:
    """Return a stable rounded failure ratio for aggregate output."""
    if evaluated_row_count == 0:
        return 0.0
    return round(failure_count / evaluated_row_count, 6)


def _parse_dates(values: pd.Series) -> pd.Series:
    """Parse date-like values with deterministic pandas coercion."""
    return pd.to_datetime(values, errors="coerce").dt.normalize()
